GET http://localhost:4200/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzFjNTFmNTFiYWZiMmJhNzc3ZmJmNTAiLCJpYXQiOjE2NjI4MDQwMDV9.fTv0TfxBYsCTuU6yPQlyWYH3yFolkI5dHR6wNTIppuo